kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: kafka
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    ports:
      external: 9094
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
metrics:
  kafka:
    enabled: true
  serviceMonitor:
    enabled: true