apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "otus-hw04.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "otus-hw04.fullname" . }}-service
                port:
                  number: {{ .Values.application.service.port }}