replicaCount: 1

application:
  deployment:
    pod:
      repository: slava1309/hw6
      pullPolicy: Never
      tag: v1
      port: 80
  service:
    type: LoadBalancer
    port: 8000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"



